### ISSUE TITLE
Spacing between \+ and \2 not correct

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#12]
```latex
\avmtmp{
			[\punk{head|aux}{$+$}\\
		         light & $+$\\
			 comps & < \1 > \+ \2 < NP > ]
			}
```
![Bildschirmfoto 2020-05-07 um 12 17 14](https://user-images.githubusercontent.com/4655859/81283397-da2d1500-905c-11ea-8ba5-73bce150c1ad.png)

There seems to be more space after the \+ than before it.

**Comment by kopeckyf** [comment]
This is the same as #23. Please check for already open issues when you open new ones.
