### ISSUE TITLE
lists with italics \phonliste

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#13]
Right now I use:
```latex
\avmtmp{
            [phon  & \phonliste{ considers } \\
             subj  & < \3 NP >\\
             comps & < \1, \2 [ subj & < \1 >  ] > ]		
          }
```
to produce:
![grafik](https://user-images.githubusercontent.com/4655859/81289133-2b8dd200-9066-11ea-9e39-bf68f5718f98.png)

The italics lists is needed quite often. Maybe it is possible to find a good shortcut here. Or maybe even have a configurable hack that looks at the feature (PHON) and then says: Great we do the value in italics. 

Right now the values are set in small caps. 
![grafik](https://user-images.githubusercontent.com/4655859/81289914-73f9bf80-9067-11ea-9672-a9cb455e371e.png)

This seems wrong. All values should be in normal font.  If we have NP[nom] in brackets, they should not be small caps. Somehow the NPs seem to come out allright. Do not understand, why `considers` is small caps.

**Comment by kopeckyf** [comment]
- NP comes out in capitals because only lowercase letters are set in small caps - try entering `< \3 np >` to see the effect.
- "considers" is in small caps because `<` creates a new sub-structure. The first column of a sub-structure is always typed in the `attributes` font, which defaults to `\scshape`. The same goes for `NP[nom]`

**Comment by stefan11** [comment]
Ah, I see. Could one change this? I guess it will confuse many, many users. The idea would be to somehow check whether their is an attribute value pair and if it is not, it is either an atomic type (a value) and should be in italics or it is a PHON list: < gave, a book, to Mary > and this could be in italics too.

One could develop a special setting that checks for every feature whether there is a corresponding font command and then use this font command in the respective structures.

So if there is \newcommand{\phonfont}{\itshape} and the avm package sees PHON it calls this font feature in the following structure and for the following feature (in case it is simple).

**Comment by kopeckyf** [comment]
Well, that small caps only work on lowercase characters is a basic fact of TeX, and we can't change it. There is a command `\MakeLowercase`, but of course it needs to be applied selectively. 

I suspect that any automatic checks for the content of an AVM will be costly in terms of escalating run time requirements.

The solution I would favour is to enable users to adjust the `style=` of substructures as well. Right now, the `style` can only be applied for a complete AVM. But in the future it should be possible to write, e.g. `style=phon` to a single **sub**-structure. I will investigate the best implementation for this.

**Comment by stefan11** [comment]
The competition you are facing [=:-)] is \phonlist{ john, loves, mary }. What I am trying here is to come up with something better, more readable. I do not know what the runtime impact would be. Currently lots of my runtime in the HPSG handbook goes to biblatex ...

**Comment by kopeckyf** [comment]
This issue will now be tracked under #2, which is the more general idea for which this a concrete usage case.

**Comment by kopeckyf** [comment]
@stefan11 I have been thinking about how to do this the best way. Here are some ideas:

1. One could let the user define special commands that both output a user-defined string and govern the layout of the sub-structure that is immediately following. E.g.:

```
\avm{
            [\phon < considers > \\
             subj  & < \3 NP >\\
             comps & < \1, \2 [ subj & < \1 >  ] > ]		
          }
```

Here, `\phon < considers >` would be output as "type PHON, move to the next column, open a list substructure `<>` and apply the `phonlist` style to this structure (and only to it), which is basically `font=\itshape`.

2. Another possibility would be to give style directions in the cell they should apply to, e.g.

```
\avm{
            [phon  &  <\style{phon} considers > \\
             subj  & < \3 NP >\\
             comps & < \1, \2 [ subj & < \1 >  ] > ]		
          }
```

3. Alternatively, `\style{phon}` could be replaced by a shorter syntax, e.g.

```
\avm{
            [phon  &  <#phon considers > \\
             subj  & < \3 NP >\\
             comps & < \1, \2 [ subj & < \1 >  ] > ]		
          }
```

Personally, I'd prefer option (1). Any comments are welcome

**Comment by Glottotopia** [comment]
note that # is commonly used for IDs in programming, eg in CSS

**Comment by kopeckyf** [comment]
@stefan11 with `\avmdefinecommand` from https://github.com/langsci/langsci-avm/commit/96051f980d1a01afb6092e475f037eadb5fea9e6, it is now possible to pre-define custom layout for sub-structures. 

Example based on your original issue report:

```
\avmdefinecommand {phon}[phon] { attributes=\itshape } % define a new \phon command

\avm[style=narrow]{
	[\phon <  considers > \\ % use the new \phon command
	subj  & < \3 NP >\\
	comps & < \1, \2 [ subj & < \1 >  ] > ]		
}
```

Result:
![testenv](https://user-images.githubusercontent.com/10461729/85588688-34049100-b643-11ea-8e34-b1fdd5acccc7.png)

`\avmdefinecommand` has the following syntax (I'll add some documentation in the next days):

```
\avmdefinecommand {name of \command} [label] * {style definitions}
```

If `*` is given, then the `\command` won't automatically advance to the next column when it is used in `\avm`. `{style definitions}` should be exactly as those in `\avmsetup`. Commands thus created are only available in the scope of `\avm`, i.e. you can have a totally different definition of `\command` outside of `\avm`.

Problems may arise if the structures are becoming too complex. As always, I'm grateful for feedback.
