### ISSUE TITLE
\asort instead of \type

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#14]
The standard for types in avm.sty is `\asort`. To help people with conversion we should have `\asort` too.

```latex
  \begin{avm}
    \[\asort{word}
    synsem$|$local & \[category & \hspace{-1.9cm}\[head & noun\]\\
                     content$|$index$|$number & plural\]
    \]
  \end{avm}
```

**Comment by kopeckyf** [comment]
No.

**Comment by kopeckyf** [comment]
The reason why we have `\asort` in oldskool `avm` is to distinguish it from `\osort`. This is old, deprecated, and unintelligible code that we will not support.

**Comment by stefan11** [comment]
Do we have \osort? Some linguists prefer to talk about sorts rather than types. I guess \sort is taken but maybe we can use \sort within the avm environment.
