### ISSUE TITLE
Maybe have the value font even without & delimiter

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#15]
This is the situation:

```latex
\avmtmp{
[\type*{word}
 synsem|local & [category [ head & noun ]\\
                 content|index|number plural ] ]
}
```
With an alignment the line `content|index|number` would stick out. Without alignment `plural` comes out in small caps. An idea I had is to take everything after a blank to be the value. If peopple want to have feature names with blanks they have to use `~`. Would this be possible? Would be great.

**Comment by kopeckyf** [comment]
> With an alignment the line content|index|number would stick out

It looks good to me, can you tell me what is wrong with this output?

![plural](https://user-images.githubusercontent.com/10461729/81561588-b0912800-9393-11ea-9c91-c47b4d168920.png)

**Comment by stefan11** [comment]
Hm. Strange. In formal-background.tex of the HPSG handbook, I get this:
![grafik](https://user-images.githubusercontent.com/4655859/81572088-0e793c00-93a3-11ea-81a4-02ddf4b6a910.png)

Maybe we should track this one done. Maybe we would also find the reason of the \rm, \sc, \it frustration.

**Comment by kopeckyf** [comment]
I think the difference between yours and mine output is the column separator `&`, which is present in mine but not in yours. Still, is there anything you'd like to change in either of our outputs? What is wrong with yours?

**Comment by stefan11** [comment]
```plural``` should be in italics not in small caps. The idea was to treat things as the value even if there is no `&` but just a space. So a space or an `&` would cause everything that follows to be seen as a value but only the `&` would trigger alignment.

But maybe one does not need it since one can either insert the `&` as above or use `\punk`.

**Comment by kopeckyf** [comment]
Personally, I'd think that separating attributes and values via spaces would be very risky. What about attributes that contain spaces, or values that do? 

I don't see why the classical `&` shouldn't be a good separation.

**Comment by stefan11** [comment]
Attributes with spaces could use `~`. I close this for now. I think the `&` works.
