### ISSUE TITLE
Improve the appearance of vectors with wide contents

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#16]
The following code produces scrambled output:
```latex
  \avm{
    [phon \3\\
     non-hd-dtrs|first|phon \1\\
     head-dtr|phon \2 ]
  }
```
![grafik](https://user-images.githubusercontent.com/4655859/81470851-5e160700-91ed-11ea-8337-0f7abff63f92.png)

An & is needed but then there is too much space after \1:
 ```latex
 \avmtmp{
    [phon \3\\
     non-hd-dtrs|first|phon \1&\\
     head-dtr|phon \2 ]
  }
```

**Comment by kopeckyf** [comment]
The `avm` is not in the expected input, since it only has 1 column (so it's a vector). I will investigate though whether the display of one-columned vectors can be improved.

In the meantime, please treat this as a punk:

```
\avm{
	[phon & \3\\
	\punk{non-hd-dtrs|first|phon}{\1}\\
	\punk{head-dtr|phon}{\2} ]
}
```

![punks](https://user-images.githubusercontent.com/10461729/81561094-eda8ea80-9392-11ea-87c1-f05d55bd547e.png)

**Comment by stefan11** [comment]
I know Punks need much space, but in the example there is too much space after the Punk, that is, the space after [1] is too big in your solution too. The result is like having a & after the [1]. Which may be an independent bug.

**Comment by kopeckyf** [comment]
Indeed `\punk` was missing additional space. This is now fixed.

Still, this issue should remain open to see if the appearance of vectors with large widths can be improved.

**Comment by stefan11** [comment]
I was complaining about too **much** space after the [1] in your figure above. But maybe this is fixed now.

**Comment by kopeckyf** [comment]
> I was complaining about too **much** space after the [1] in your figure above. But maybe this is fixed now.

@stefan11 Sorry for the late reply. Yes indeed the spacing issue is fixed since 868dc2cc6e0b1254bb22e375cd91ee84474b74f1 (or thereabouts)

**Comment by kopeckyf** [comment]
@stefan11 in the newest Version of langsci-avm (v0.3 rc-5), you can use the option `align=false` to have a feature matrix with non-aligned columns. They are separated by `&`, which produces a horizontal skip equal to `vectorsep`, which defaults to `1em`. When the feature "vectors" contain a lot of contents, `1em` seems good to me. However, in the case from this issue, a lower separator of `0.5ex` seems better (the default column separator in two-column AVMs):

```latex
\avm[align=false, vectorsep=0.5ex]{
	[phon & \3\\
	non-hd-dtrs|first|phon & \1\\
	head-dtr|phon & \2 ]
}
```
![vector](https://user-images.githubusercontent.com/10461729/111751812-35db4800-8895-11eb-9f7e-56eddfd66bb3.png)

If you find a `vectorsep` that works better for you than `1em`, please let me know and I might change the default in the package. You can always set a default to apply in all AVMs of your document with 
`\avmsetup{vectorsep=123mm}`.

This may or may not work without column separators `&`.  I can't offer any support if this doesn't work without `&`. The benefits of having the `&` are two-fold:
 
 - Better semantics
 - Separation of content and layout
 - One can easily switch between aligned and non-aligned AVMs.

(If you know Chris Manning's `avm` package, you might be familiar with unaligned matrices. But in Manning's package, you had to replace `&` with `\;`. So I hope this will be an improvement in my code over the older routine)

**Comment by stefan11** [comment]
Does this solution work for embedded AVMs without alignment?

```latex
\avm{
[a & [ b & c\\
          ddddddd & e ]\\
 f & g ]]
}
```
So what if the inner AVM is supposed to be non-aligned?

**Comment by kopeckyf** [comment]
Not yet. The setting `align=false` can only be applied to the complete matrix. Applying settings locally for sub-structures are currently under development (see #2).
