### ISSUE TITLE
Square brakets around features of XPs and space after box

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#17]
A quite frequent pattern is that somebody talks about valency lists like

```latex
comps < NP[\type{nom}] >
```
![grafik](https://user-images.githubusercontent.com/4655859/81473922-544ace80-9202-11ea-90d6-1574d548e66d.png)

In this AVMs the square brackets are too large. The square brackets should come out as normal text. One way to achieve this is to use `!`:
```latex
comps < !NP[\type{nom}]! >
```
But with this trick the distance between `\1`and the following NP is too short:
![grafik](https://user-images.githubusercontent.com/4655859/81473906-38472d00-9202-11ea-8889-978a54a3e517.png)

The preferred behavior would be that the type of brackets is detected automatically. If we have
```latex
[ v1, v2, ..., vn ]
```
This is a list of values and normal brackets should be used. 
If we have 
```latex
[ feature & value ]
```
Normal brackets could be used as well. (Let's see how this looks)

AVM brackets are needed for
```latex
[\type*{type}
 feature & value ]
```
and
```latex
[feature1 & value1\\
 feature2 & value2 ]
```

This would have smaller square brackets too:
![grafik](https://user-images.githubusercontent.com/4655859/81474692-7266fd80-9207-11ea-8605-c9ebb6d4a7d4.png)
```latex
\avm{
		[arg-st & < \ldots, \3, \ldots >\\
		comps & <\ldots, \3[loc & \1], \ldots >\\
		slash & \2
		]
	}
```

**Comment by kopeckyf** [comment]
`style=narrow` was designed to treat such cases as the example you sent:

```
\avm[style=narrow]{
	[arg-st & < \ldots, \3, \ldots >\\
	comps & <\ldots, \3[loc & \1], \ldots >\\
	slash & \2
	]
}
```

**Comment by kopeckyf** [comment]
For the structures to which `style=narrow` can't be applied, this issue is tracked under #21
