### ISSUE TITLE
italics correction seems to be not working

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#18]
If we have an `l` ending a type name, it seems to be too close to the bracket.
![grafik](https://user-images.githubusercontent.com/4655859/81474232-3ed6a400-9204-11ea-9a4f-9a56d3877e87.png)

```latex
\avm{[cat|head & verb \\
	cont & move-rel ]}
```

**Comment by kopeckyf** [comment]
Thanks! This is due to the usage of `\itshape`, which doesn't automatically insert the italic correction - unlike `\textit{}`, which does.

**Comment by kopeckyf** [comment]
Solved by https://github.com/langsci/langsci-avm/commit/201bce26e43f99cabf1e314c350fda5152df57ac
