### ISSUE TITLE
Enable setting options locally

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langsci-avm#2]
Currently one can set the options, e.g. `attributes` only for the *whole*  content of an `\avm`. It would be great if one could change these options mid-way, e.g. if one sub-structure should have a different font in the first row than the other parts of the same parent structure.

**Comment by stefan11** [comment]
Thanks for the \list treatment. The brackets following it are too big and the content within the brackets should be in italics as well. Since list is something like \phon (as I understand it), this could be included in the definition of \list.

**Comment by kopeckyf** [comment]
`\phon` and `list` are not actually shipped with `langsci-avm`. The function that is shipped is `\avmdefinecommand`, which is a [factory function](https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)), a function that defines other functions.

You have to build and run your own factory to produce commands like `\phon` and `\list`. The upside is that you have maximum flexibility, but the downside is that you have to employ your own factory workers. And beware, these workers formed a trade union and they are vicious - if you try to have the factory produce anything that is not in the union labour agreement, the least thing that will happen is that they go on strike and your factory won't output anything. But they might even resort to sabotage, and then your documents will stop compiling.

I'll add more documentation on `\avmdefinecommand` later today, but here's how you could make a really narrow list with italics:

```
\avmdefinecommand{phon}[phon]
  { 
    attributes=\itshape, 
    delimfall=10pt,
    delimfactor=900
  }
```

Edit: This will create two commands within the scope of `\avm{}`, `\phon` and `\phon*`. Note that earlier, you had to define the starred variant manually, but `\avmdefinecommand` now produces both the starred and the non-starred variant. The difference is: The normal variant advances to the next column after printing its label, and the starred variant does not.

**Comment by kopeckyf** [comment]
`\avmdefinecommand` is now described in more detail on page 6 of the documentation for Version 0.2.
