### ISSUE TITLE
Insert space where authors don't (\2\-list)

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#20]
```latex
\avm{
			[subj & \1 \\
			 comps & \2\-list(gap-ss) \\
			 deps & < \1 > \+ \2
			]
		}
```
produces
![grafik](https://user-images.githubusercontent.com/4655859/81474887-a393fd80-9208-11ea-896d-7fef458ceaef.png)
but it should produce:
![grafik](https://user-images.githubusercontent.com/4655859/81474910-c8887080-9208-11ea-80aa-ea39c8c2a624.png)

Not sure whether this has to be done in the style or whether editing could add the space manual.

**Comment by kopeckyf** [comment]
You've mentioned it in the title: It is important that authors write what they mean.

**Comment by stefan11** [comment]
So this is a won't fix? Maybe you give such things this label so that I know what is going on or rather not going on =;-).
