### ISSUE TITLE
Space after \shuffle is missing

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#22]
```latex
\avm{
		[\type*{word}
		head & verb \\
		val|comps & \1 \shuffle \2 \\
		clts & elist
		]
	}
```
produces

![Bildschirmfoto 2020-05-09 um 15 28 04](https://user-images.githubusercontent.com/4655859/81475023-ba871f80-9209-11ea-8380-3787200dcfe1.png)

A space before the `\2` is missing.

**Comment by kopeckyf** [comment]
The issue here is that `\shuffle` is a control word and so spaces after it are gobbled (compare `\LaTeX` etc.). In order to avoid the space, you need to write `{\shuffle}`, `\shuffle{}` or `\shuffle\`.

There would be a solution to do this internally, but this would only work in some cases. For example, if there was some punctuation after `\shuffle`, the spacing would again be wrong. Caveats would also apply to a `\xspace` solution, but of course users are free to define a local command `\Shuffle{\shuffle\xspace}`.

**Comment by kopeckyf** [comment]
One solution I was thinking would be to summarise all the commands that express relations, i.e. `\+`, `\-`, and `\shuffle` into a single `\rel` command, and then the argument to that command would govern the relation that is output. 

E.g. `\rel{+}` : ⊕
       `\rel{-}` : ⊖

Btw, the commands could also be written in the sloppy form `\rel+`, `\rel-` if the argument is a symbol.

Bonus: There would be the user-customisable `\avmdefinerelation` by which the user could set-up custom relations and their output. Eg. `\avmdefinerelation{love}{♥}` => `x \rel{love} y ` => x ♥ y

This way, we would have better control over the spacing before and after relations, which would also affect issue #23. 

What do you think @stefan11

**Comment by stefan11** [comment]
Hm. My goal is to reduce clutter. It should look almost like a real avm. \rel{+} is to much. The need to input a x ♥ y is rather restricted in science. =:-) What a dry bussines. I would go for the \xspace solution. This seems great.

**Comment by stefan11** [comment]
\shuffle{} is not better than $\oplus$. \shuffle without brackets would be.

**Comment by kopeckyf** [comment]
There's now an automatic `\thinmuskip` following `\shuffle`, which will correct the spacing.

However, I'm now more and more convinced we need a command `\rel` that is user-configurable, i.e. users should be able to insert their own relations and operators. There will almost certainly be users in the future who'd like to use other relations than concatenation and subtraction. 

E.g. users might want to use the squared plus ⊞, or `\boxplus`. Then they should have an interface to say:

```
\avmdefinerelation{+}{$\boxplus$}
\avm { a \rel{+} b }
```

However, you will always be able to use `\+` and `\shuffle` via the `customise` option I installed in https://github.com/langsci/langsci-avm/commit/f3874ab2d1d536719e7ed4ce5a622bc0ecde3995. You can use `\avmoptions{customise = { ... } }` to define local commands available in every AVM.

**Comment by stefan11** [comment]
I think `\rel` would be nice but maybe people will just type the math mode version. It is good to have \+ and \shuffle though since they are in every paper.
