### ISSUE TITLE
too much space after \+ and \-

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#23]
![grafik](https://user-images.githubusercontent.com/4655859/81475064-fcb06100-9209-11ea-8ff8-b4cfe196ae5e.png)

```latex
\avm{
			[subj  & \1 \\
			 comps & \2 \- list(gap-ss) \\
			 deps  & < \1 > \+ \2
			]
		}
```

**Comment by kopeckyf** [comment]
I've still not discovered the root of this error, but a workaround is to adjust the spacing manually. For some reason still to be investigated, `\,` is the perfect fit:

```
\avm{
			[subj  & \1 \\
			 comps & \2 \-\,list(gap-ss) \\
			 deps  & < \1 >\,\+ \2
			]
		}
```
