### ISSUE TITLE
alignment strange

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#24]
```latex
\avm{
 [form & F(\1, \ldots) \\
  i-form \1 ]}
```
produces
![grafik](https://user-images.githubusercontent.com/4655859/81475193-e8b92f00-920a-11ea-8741-393afbc85b49.png)

I like the result, but shouldn't the F be starting to the right of `\1`?

**Comment by kopeckyf** [comment]
You have inserted `F` to the left of `\1`. Why should it appear to the right of it??

**Comment by stefan11** [comment]
Sorry, this was imprecise. Lets use a differently numbered box:
```latex
\avm{
 [form & F(\1, \ldots) \\
  i-form \2 ]}
```
The F should be after the \2. Like having a table:
```latex
form      & F(\1, \ldots) \\
i-form \2 & \\
```

**Comment by kopeckyf** [comment]
Ah, I see, but isn't this already possible? 

```
\avm{
	[form & F(\1, \ldots) \\
	i-form \1 & ]}
```

![table](https://user-images.githubusercontent.com/10461729/81580790-2c986980-93ae-11ea-859e-e94632079dba.png)

**Comment by kopeckyf** [comment]
If you'd like there to be less space between the `F(\1,...)` in the first row and the `\1` in the second, why not use:

```
\avm[columnsep=0pt]{
	[form & F(\1, \ldots) \\
	i-form \1 & ]}
```

**Comment by stefan11** [comment]
I think there was a bug in the original treatment. I do not complain about any result of formatting. I just was very supprised to see that the `&`is ignored if there is no corresponding `&`in the second row.
