### ISSUE TITLE
please ignore this for the moment

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#25]
![Bildschirmfoto 2020-05-09 um 11 06 34](https://user-images.githubusercontent.com/4655859/81469447-286d2000-91e5-11ea-86ad-972f522f7c76.png)

**Comment by kopeckyf** [comment]
Kindly only post complete issues.

**Comment by stefan11** [comment]
Yes, sorry, but I started editing this and there seems to be no way to ave this without opening an issue.
