### ISSUE TITLE
alignment if & is missing

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#28]
```latex
\avm{
	          [head|vform  \type{fin}\\
		   subj  < \1 NP >\\
		   comps < > ]}
```

comes out as 

<img width="148" alt="grafik" src="https://user-images.githubusercontent.com/4655859/84506958-636ce280-acc0-11ea-9f5a-bf4cd8be1436.png">

**Comment by kopeckyf** [comment]
Well, the input does not match the input specification of the package. It expects a collection of attributes and values, but in this example, no values are given. Why don't you use:

```
\avm{
	          [head|vform  & \type{fin}\\
		   subj  & < \1 NP >\\
		   comps & < > ]
}
```

**Comment by kopeckyf** [comment]
Probably a duplicate / instance of #16

**Comment by stefan11** [comment]
This is what authors do. And it is what worked in tabular environments. And in the old AVM package.

**Comment by kopeckyf** [comment]
@stefan11 Just to make sure my understanding is correct: In the example you posted, is `fin` in the first row a value to `head|vform` or is it a type? Curious about which object in the HPSG ontology _fin_ belongs to.

**Comment by stefan11** [comment]
It is a value. It is always:

type
feature1 value1
feature2 value2
feature3 value3

The values are either atomic types like _fin_ or types that have features with values.

So yes, you are right, we should even get rid of the \type specification and just have the &. 
```
\avm{
	          [head|vform  & fin\\
		   subj  & < \1 NP >\\
		   comps & < > ]
}
```

This (and \punk) is what I did now.

I think authors write things the way given in the initial example to have a compact notation.
