### ISSUE TITLE
No italics correction in lists

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#32]
There should be an italics correction for "cat":
<img width="198" alt="grafik" src="https://user-images.githubusercontent.com/4655859/89510467-e302c380-d7d0-11ea-9caf-2e5d1f3e01b5.png">

```latex
\avm{
	[\type*{phrase}
	\phon  < the, cat >\\
	synsem & \upshape NP ]
}
```

**Comment by kopeckyf** [comment]
The difference is hard to spot:

Without italic correction:

![grafik](https://user-images.githubusercontent.com/10461729/93776510-e5579a80-fc23-11ea-853b-b849b0172b46.png)


With italic correction:

![grafik](https://user-images.githubusercontent.com/10461729/93776557-f56f7a00-fc23-11ea-8cd3-7cb0e2452502.png)

**Comment by stefan11** [comment]
Hm. Thanks. Should we add a bit more space? But maybe this is wrong when we do not have a letter getting close to the closing bracket. If one compares the space at the beginning of the list with the space at the end it looks uneven.

**Comment by kopeckyf** [comment]
There is a slight difference compared to the kerning that, e.g. `$\left< cat \right>$` would have. However, the forces at work here could not be determined based on what is written in the TeXbook and in TeX by Topic, and no information could be obtained from user groups and TeX.SE. As long as we don't understand the issue, I wouldn't do anything about it.
