### ISSUE TITLE
Distance between lines is different

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#33]
<img width="489" alt="grafik" src="https://user-images.githubusercontent.com/4655859/89510999-9cfa2f80-d7d1-11ea-950c-ecaa6e2d8e1b.png">

```latex
\avm{
		[\type*{headed-phrase}
		phon & \list*(phon)\\
		synsem & synsem\\
		dtrs & \list*(sign)\\
		hd-dtr & sign ]
	}
```
There is more space after lines with brackets than before. This looks strange. 

This is the setup:
```latex

\avmsetup{columnsep=.3ex,style=narrow}

\avmdefinecommand{phon}[phon]
  {
    attributes  = \itshape%,
%    delimfactor = 900,
%    delimfall   = 10pt
}
\avmdefinecommand{form}[form]
  {
    attributes  = \itshape%,
%    delimfactor = 900,
%    delimfall   = 10pt
}

\avmdefinecommand{list}[list]{ attributes=\itshape } % define a new \list command
   % Note: the label "list" will be out put in whatever font is currently active.
```

**Comment by kopeckyf** [comment]
This is due to the setting `extraskip`. In langsci-avm, every line that ends with a delimiter is followed by `\smallskip` by default. This is to ensure that delimiters in subsequent lines do not clash. It is often very helpful.

There are two ways to disable this behaviour (also noted in the doc): 

- by placing `\relax` before the `\\` in the respective line
- by setting `extraskip = 0pt` either locally to `\avm[extraskip=0pt]` or super-locally to `\avmsetup{extraskip=0pt}`

**Comment by stefan11** [comment]
Hm. Very strange. I think this worked perfectly well until recently. Authors are not supposed to place \relax into AVMs. This should work automatically.

**Comment by kopeckyf** [comment]
Automatisation of this and similar procedures will only be possible in a proper, comprehensive DAG representation of AVMs. 

There'll be the option shortly to have extra line skip in every line, not only those that end with a delimiter (i.e. `extraskip` is applied to every line).

The behaviour changed quite recently, that is correct. I believe the change was made after an issue was reported by a user named "Stefan Müller", but don't quote me on that.

**Comment by stefan11** [comment]
Yes. This is probably true. I do not understand all the consequences of my wishes. =:-) But sometimes this is even helpful. Two programmars could agree easily that feature X is impossible to implement but an insisting user and a programmer may come up with something new.
