### ISSUE TITLE
Closing bracket do not display correctly

### ISSUE THREAD

**Issue by Balatonia** [langsci/langsci-avm#43]
Hey,

when I use the sample code in the package description, I get the wrong output. Specifically, the closing brackets do not show up in the predicted form (the same happens with the classic avm-package). Do you know of any package incompatibilities causing this problem?

Input:

\avm{
[ ctxt & [ max-qud \\
sal-utt & \{ [ cat \\
cont <ind & i> ] \}
]
]
}

Output: 

[Bildschirmfoto 2021-07-06 um 11.46.05.pdf](https://github.com/langsci/langsci-avm/files/6769080/Bildschirmfoto.2021-07-06.um.11.46.05.pdf)

**Comment by Glottotopia** [comment]
Thanks for getting in touch. Please provide a full minimal working example (MWE). The following code works fine on my machine 
```
\documentclass{standalone}
\usepackage{langsci-avm}
\begin{document}
\avm{
[ ctxt & [ max-qud \
sal-utt & { [ cat \
cont <ind & i> ] }
]
]
}
\end{document}
```
![Screenshot_2021-07-06_11-57-38](https://user-images.githubusercontent.com/1553576/124583211-1885b600-de53-11eb-85f2-84e133168d04.png)


Does it work on yours? 

Presumably, you load some other packages which interfere, but without a MWE, we will not be able to tell.

**Comment by Balatonia** [comment]
Hi, I managed to resolve the problem. It was caused by a package incompatibility with \usepackage[LGRgreek]{mathastext}.
