### ISSUE TITLE
Ability to add labels to corners of AVMs

### ISSUE THREAD

**Issue by findlayjy** [langsci/langsci-avm#44]
As you mention in the docs, `avm.sty`  had a command `\(o)sort` which you could use to add labels to the corners of AVMs, with options `topleft`, `topright`, and `bottomright`. Is there a way to achieve this still? If not, it would be good to reintroduce this functionality. (For example, to reproduce some AVMs in Butt 1995 _The Structure of Complex Predicates in Urdu_, where she uses labels on the bottom right corners of her argument structure AVMs to indicate events -- see image.)
![IMG_6100](https://user-images.githubusercontent.com/26364516/145892337-421100d6-cc07-42f1-bffc-6af04b09abdf.jpg)

**Comment by kopeckyf** [comment]
In Version 0.3(rc), which is not yet on CTAN, we added the command `\id` to attach small identifiers to the bottom left of structures. Now there is also an option to move this identifier to the bottom right of a structure.

Example:
```latex
\avm[types=\normalfont, id position=south-east]
  { 
  	[\type*{de `give'}
  		\id{E}{[...]} 
  	]
  }
```

![grafik](https://user-images.githubusercontent.com/10461729/145981761-f999ddf7-0fda-4339-8f08-04b70a5b75c4.png)


When `id position` is not set or `id position=south-west` is selected, the label in `\id{<label>}{<structure>}` is placed to the bottom left of the structure.

You can include [`langsci-avm.sty`](https://github.com/langsci/langsci-avm/blob/master/langsci-avm.sty) in your working directory to use this feature. Please also see [the updated documentation](https://github.com/langsci/langsci-avm/blob/master/langsci-avm.pdf) for examples of using `\id{<label>}{<structure>}`.

I tested the new `id position` setting only rudimentary. If you see anything wrong, kindly reply to this issue. If you are satisfied with the output, please close this issue.

**Comment by findlayjy** [comment]
Thanks! This looks great. One issue: it seems to have affected the behaviour of the escape/switch symbol `!` -- inside the second argument of `id`, it simply gets printed as a character and doesn't affect the sizing of any parentheses within pairs of `!`s.

**Comment by kopeckyf** [comment]
@findlayjy This issue is related to #38: The escape mode only works on the top level of grouping inside an AVM. In particular, it does not work inside the grouped arguments of commands.

My current approach is to find an alternative for escaping, e.g. grouping. I hope to complete this approach in the next few weeks. Sorry about the delay.

**Comment by kopeckyf** [comment]
@findlayjy, apologies for the long delay in processing this issue! In https://github.com/langsci/langsci-avm/commit/70ef0376c2f28739ff39799876ffd9ce3659d093 I changed the way that escaping, and parsing in general, works in `langsci-avm`. It is now possible to escape even when `\id` is used. Would you like to take a look at the new [`langsci-avm.sty`](https://github.com/langsci/langsci-avm/blob/master/langsci-avm.sty) and let me know what you think? 

![grafik](https://user-images.githubusercontent.com/10461729/218731995-b1d90344-05c3-4b8e-b3c3-9715cfd70c77.png)


```latex
\avm[types=\normalfont, id position=south-east, align=false, stretch=1]
{ 
  [\type*{de `give'}
	\id{E}{
	  [
            % Please note that you have to escape every single line
	    !CS([$\alpha$], GO\textsubscript{\itshape Poss}([ ], TO[ ]))!\\
	    !AFF([ ]$^\alpha$)!\\
            !ASP(\_\,\_\,\_)!
	  ]
	} 
  ]
}
```

**Comment by findlayjy** [comment]
Thanks for letting me know about this change! Issue is now definitely resolved :)
