### ISSUE TITLE
add space between lines if neighboring lines contain brackets

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#6]
![Bildschirmfoto 2020-03-26 um 12 14 15](https://user-images.githubusercontent.com/4655859/77640972-8a3a3900-6f5b-11ea-80f4-3f77b7f3f968.png)

\avmtmp{
[ \punk{synsem|loc|cat|comps}{\1 \+ \2}\\
  head-dtr      & [ synsem|loc|cat|comps \1 \+ < \3 > \+ \2 ] \\
  non-head-dtrs & < [ synsem \3 ] > ]
}

It would be great if this situation could be automatically detected and a \smallspace could be inserted. The situation between line 1 and 2 may be ok but not if there are two lines with brackets that could touch each other.

Interessant ist, darüber nachzudenken, was pasiert, wenn die Werte von head-dtr und non-head-dtrs nicht aligniert sind. Dann würden sich die Klammern nicht berühren.

Man kann jetzt entweder versuchen, das richtig zu detektieren. Weiß nicht, ob das geht. Oder man gibt auf und sagt, das muss immer per Hand gemacht werden. Oder man macht bei zwei Klammerausdrücken in benachbarten Zeilen immer Zwichenraum rein und es gibt eine Möglichkeit, das rückgängig zu machen.

**Comment by kopeckyf** [comment]
@stefan11 In the current Version 0.2-rc1, there is an automatic detection of line breaks when they come _immediately after_ the end of a (sub-)structure. The AVM

```
\avm{
	[ \punk{synsem|loc|cat|comps}{\1 \+ \2}\\
	head-dtr & [ synsem|loc|cat|comps \1 \+ < \3 > \+ \2 ] \\
	non-head-dtrs & < [ synsem \3 ] >\\
		non-head-dtrs & < [ synsem \3 ] > ]
}
```
compiles this output:
![langsci-avm-02rc1-1](https://user-images.githubusercontent.com/10461729/81172983-90322980-8f9f-11ea-9630-080a4847bd2a.png)

Also, Version 0.2-rc1 has a `style` option. Setting `style=narrow` will result in this output:

![langsci-avm-02rc1-2](https://user-images.githubusercontent.com/10461729/81173093-c7a0d600-8f9f-11ea-801b-b4c5ba0b3f90.png)

**Comment by stefan11** [comment]
Looks good, what does it mean to have style "narrow"? How does this look as code? Maybe using \\< and \\> would be more intuitive.

**Comment by kopeckyf** [comment]
The appearance of angle brackets is improved in Version 0.2.0. I think it is unnecessary to have two sets of inputs for angle brackets with this update (see below, left is the appearance in Version 0.1, right is the new one)

![linespacing](https://user-images.githubusercontent.com/10461729/81265476-75b18c00-9043-11ea-97ab-ee1f0e3ef558.png)

**Comment by stefan11** [comment]
Can you please show the code. It is not described in the manual how to do the small brackets. I am afraid that it introduces notational clutter, which would not be the case with the \\< \\> notation.
