### ISSUE TITLE
small brackets

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#7]
![Bildschirmfoto 2020-03-26 um 12 14 15](https://user-images.githubusercontent.com/4655859/77641394-4a278600-6f5c-11ea-8cf0-45f3d59b0275.png)

The brackets around [3] should be small. avm.sty has special codes for this: \q< and \q>.

Since we did not use \\< we may use \\< for this.

**Comment by kopeckyf** [comment]
In Version 0.2, this can be achieved with `style=narrow`.

**Comment by stefan11** [comment]
I inteded to write \\< but github swallows the \\, if one writes only one.
